//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CasadeModa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Articol
    {
        public int IdArticol { get; set; }
        public string Titlu { get; set; }
        public string Descriere { get; set; }
        public string Imagine { get; set; }
        public Nullable<System.DateTime> DataPublicare { get; set; }
        public string Continut { get; set; }
        public Nullable<bool> Status { get; set; }
        public int IdCategorie { get; set; }
    
        public virtual Categorie Categorie { get; set; }
    }
}
