//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CasadeModa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Culoare
    {
        public Culoare()
        {
            this.DetaliiFacturas = new HashSet<DetaliiFactura>();
        }
    
        public int IdCuloare { get; set; }
        public string DenumireCuloare { get; set; }
    
        public virtual ICollection<DetaliiFactura> DetaliiFacturas { get; set; }
    }
}
