//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CasadeModa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetaliiFactura
    {
        public int IdDF { get; set; }
        public Nullable<int> IdFactura { get; set; }
        public Nullable<int> IdProdus { get; set; }
        public Nullable<int> CantitateProdus { get; set; }
        public Nullable<float> PretUnit { get; set; }
        public Nullable<int> PretTotal { get; set; }
        public Nullable<int> IdCuloare { get; set; }
        public Nullable<int> IdMarime { get; set; }
    
        public virtual Culoare Culoare { get; set; }
        public virtual Factura Factura { get; set; }
        public virtual Marime Marime { get; set; }
        public virtual Produ Produ { get; set; }
    }
}
