//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CasadeModa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Factura
    {
        public Factura()
        {
            this.DetaliiFacturas = new HashSet<DetaliiFactura>();
        }
    
        public int IdFactura { get; set; }
        public string NrFactura { get; set; }
        public Nullable<System.DateTime> DataComanda { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<bool> StatusLivrare { get; set; }
        public Nullable<System.DateTime> DataLivrare { get; set; }
        public float CostTotal { get; set; }
        public Nullable<int> IdMembru { get; set; }
        public Nullable<int> IdClient { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual ICollection<DetaliiFactura> DetaliiFacturas { get; set; }
        public virtual Membru Membru { get; set; }
    }
}
