//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CasadeModa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Marime
    {
        public Marime()
        {
            this.DetaliiFacturas = new HashSet<DetaliiFactura>();
        }
    
        public int IdMarime { get; set; }
        public string DenumireMarime { get; set; }
    
        public virtual ICollection<DetaliiFactura> DetaliiFacturas { get; set; }
    }
}
