//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CasadeModa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Membru
    {
        public Membru()
        {
            this.Facturas = new HashSet<Factura>();
            this.Programaris = new HashSet<Programari>();
        }
    
        public int IdMembru { get; set; }
        public string username { get; set; }
        public string parola { get; set; }
        public string Nume { get; set; }
        public string Prenume { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> DataNasterii { get; set; }
        public string Telefon { get; set; }
        public Nullable<System.DateTime> DataInregistrare { get; set; }
        public string Adresa { get; set; }
        public Nullable<bool> Status { get; set; }
        public int IdRol { get; set; }
    
        public virtual ICollection<Factura> Facturas { get; set; }
        public virtual Rol Rol { get; set; }
        public virtual ICollection<Programari> Programaris { get; set; }
    }
}
