//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CasadeModa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Programari
    {
        public int IdProgramare { get; set; }
        public System.DateTime Data { get; set; }
        public System.TimeSpan Ora { get; set; }
        public Nullable<int> IdClient { get; set; }
        public Nullable<int> IdMembru { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Membru Membru { get; set; }
    }
}
